### PR TITLE
Further developments

### PR DESCRIPTION
**Pull request by mmasciov**
This PR:
- Adds histograms/refine binning choices;
- Adds an option not to tar package for condor submission;
- Adds (in the looper) muon PF isolation in a cone of 0.4;
- Adds (in the looper) dφ and dη wrt. the nearest jet in dR;
- Adds histograms filled with looper additions;
- Other minor improvements.

### CODE REVIEW

**Comment by CeliaFernandez** [comment]
Just to document the last commit:

- **condor/runScoutingHistos_onCondor.sh:** Changed the condition to read the parameter assignment, because jobs only taking 2 parameters without "notag" option set were crashing.
- **condor/runScoutingHistos_onCondor.sub:** Increased the number of events analyzed per data as the looper output was exceeding the old one in some cases. Also added MC and signal.
- **fillHistosScouting.py:** Correct some variable names
- **plotHistosScouting.py:** Add option to plot Monte Carlo and also done some minimal style modifications

**Comment by CeliaFernandez** [comment]
I have finished to update the code to the latest version that was used to produce the plots shown during the last weeks. I'd propose to merge it now as the master has an outdated version of the filler wrt to the skimmer and looper. I can take care of the merging conflicts, they arised because I have in this branch some of the looper updates that are already implemented in the master.

**Comment by danbarto** [comment]
I added a fix to keep the L1 seeds and HLT paths for the scouting monitor data.
Can we merge this PR or are we waiting for something else?

**Comment by CeliaFernandez** [comment]
On my side it's done and nothing else to commit to this branch as the limit implementation is being done independently

**Pull request merged**
